project:
  type: website
  output-dir: docs


website:
  title: "Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/colton-haight-672487347/?trk=opento_sprofile_goalscard
      - text: "Resume"
        href: cv/cv.qmd
      - text: "Cover Letter"
        href: Colton_Cover_Letter_copy.pdf
format:
  html:
    theme: darkly
    css: styles.css



